// <auto-generated />
namespace BethanyPieShop.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class removingrequiredfromproductname : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(removingrequiredfromproductname));
        
        string IMigrationMetadata.Id
        {
            get { return "202008270545237_removing required from product name"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
